const LEERPLANDOELEN = {"koppelingen": [{"code": "II-OrLo-a LPD 1", "doel": "Je handelt in teamverband, kwaliteitsbewust, economisch en duurzaam.", "waar": ["Missie 0: professioneel werken in de klas", "START@WORK-belofte", "casussen rond planner, deadlines, beleefdheid en werkhouding"], "evaluatie": "Attitudechecklist en reflectie"}, {"code": "II-OrLo-a LPD 3", "doel": "Je analyseert met didactische software de documentenstroom tussen aankoop, verkoop, magazijn en facturatie.", "waar": ["Documentenstroommodule", "visuele flow prijsaanvraag tot creditnota"], "evaluatie": "Documentenvolgorde en casus"}, {"code": "II-OrLo-a LPD 4", "doel": "Je illustreert organisatiecultuur, huisstijl en bedrijfsprocedures met voorbeelden zoals vestimentaire code, logo en procedures.", "waar": ["Missie 0: waarden, normen en klasafspraken", "BrightOffice-context", "professionele uitstraling"], "evaluatie": "Waarden/normen-oefening en reflectie"}, {"code": "II-OrLo-a LPD 5", "doel": "Je past consequent redactionele normen toe bij het opstellen van documenten.", "waar": ["NBN Lab", "zakelijke brief", "documentopmaak", "Smartschool en Outlook"], "evaluatie": "NBN-foutenjacht en zakelijke brief"}, {"code": "II-OrLo-a LPD 10", "doel": "Je verdeelt en beantwoordt elektronische post volgens formele communicatie en nettiquette.", "waar": ["Smartschoolmodule", "Outlookmodule", "handtekeninggenerator", "berichtsimulator"], "evaluatie": "Communicatiescore en simulatorfeedback"}, {"code": "II-OrLo-a LPD 12", "doel": "Je beheert digitale documenten volgens aangereikte criteria.", "waar": ["Planner en deadlines", "documentopmaak", "downloadbare documenten"], "evaluatie": "Controlelijst documentindiening"}, {"code": "I-II-III-GFL LPD 17", "doel": "Je gebruikt doelgericht courante functionaliteiten om digitale inhouden zoals tekst- en cijferbestanden te creëren.", "waar": ["Outlook", "NBN-brief", "documentopmaak", "PDF/downloads"], "evaluatie": "Zakelijke brief en documentcontrole"}, {"code": "I-ICT 1.1.4", "doel": "Je beheert digitale inhouden aan de hand van een aangereikte structuur.", "waar": ["Planner", "Smartschool", "documenten bewaren en downloaden"], "evaluatie": "Digitale organisatiecheck"}, {"code": "I-ICT 1.1.5 / 1.2.1", "doel": "Je creëert digitale inhouden en digitale teksten met basisfunctionaliteiten.", "waar": ["Smartschoolbericht", "Outlookmail", "zakelijke brief"], "evaluatie": "Communicatieopdrachten"}]};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-screen]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.screen)));
$('#theme').onclick=()=>{document.body.classList.toggle('dark');$('#theme').textContent=document.body.classList.contains('dark')?'Lichte modus':'Donkere modus'};
function updateProgress(){const tasks=[...$$('.task')];const done=tasks.filter(t=>t.checked).length;const pct=tasks.length?Math.round(done/tasks.length*100):0;$('#progress').style.width=pct+'%';$('#progressLabel').textContent=pct+'%'}
$$('.task').forEach(t=>t.onchange=updateProgress);
$$('.vn-quiz button').forEach(btn=>btn.onclick=()=>{$('#vnFeedback').textContent = btn.dataset.answer==='waarde' ? 'Dit is een waarde: iets wat je belangrijk vindt.' : 'Dit is een norm: een concrete afspraak die gedrag beschrijft.';});
function signatureHTML(){const n=$('#ssSigName')?.value||'[Voornaam Achternaam]';const c=$('#ssSigClass')?.value||'[Klas]';return `Met vriendelijke groet<br><br>${n}<br>${c}`;}
$('#buildSSSig')?.addEventListener('click',()=>{$('#ssSigOut').innerHTML=signatureHTML();});
$('#copySSSig')?.addEventListener('click',async()=>{const txt=signatureHTML().replaceAll('<br>','\n');try{await navigator.clipboard.writeText(txt);$('#copyMsg').textContent='Gekopieerd. Je kan dit nu plakken in Smartschool.'}catch(e){$('#copyMsg').textContent='Kopiëren lukt niet automatisch. Selecteer de tekst en kopieer handmatig.'}});
$('#checkSS')?.addEventListener('click',()=>{const s=$('#ssSubject').value.trim().toLowerCase();const b=$('#ssBody').value.trim().toLowerCase();let p=0;let out=[];if(s.length>10&&!['vraag','taak','dringend'].includes(s)){p++;out.push('✅ Je onderwerp is concreet.')}else out.push('⬜ Maak je onderwerp concreter.');if(b.includes('geachte')||b.includes('beste')){p++;out.push('✅ Je gebruikt een begroeting.')}else out.push('⬜ Voeg een begroeting toe.');if(!/geachte .*,|beste .*:/.test(b)){p++;out.push('✅ Je plaatst geen leesteken na de begroeting.')}else out.push('⬜ Verwijder het leesteken na de begroeting.');if(b.includes('met vriendelijke groet')){p++;out.push('✅ Je gebruikt het afgesproken slot.')}else out.push('⬜ Gebruik: Met vriendelijke groet.');if(!/(hey|grtz|mvg|thx|rap|\?\?\?)/.test(b)){p++;out.push('✅ Je vermijdt spreektaal en druktaal.')}else out.push('⬜ Vermijd spreektaal, afkortingen en druktaal.');$('#ssResult').innerHTML=`<b>Score: ${p}/5</b><ul>${out.map(x=>`<li>${x}</li>`).join('')}</ul>`;});
function loadGoals(){
  const target = document.querySelector('#goalsTable');
  if(!target) return;
  const data = LEERPLANDOELEN;
  target.innerHTML = data.koppelingen.map(g => `<article class="goal"><h2><code>${g.code}</code></h2><p>${g.doel}</p><strong>Waar oefen je dit?</strong><ul>${g.waar.map(w=>`<li>${w}</li>`).join('')}</ul><strong>Evaluatie</strong><p>${g.evaluatie}</p></article>`).join('');
}
loadGoals();updateProgress();
